language: python

install:
  - pip install -r requirements.txt
  - pip install -e .
  - pip install coverage

script:
  - coverage run --source correction -m unittest tests/run_tests.py

after_success: bash <(curl -s https://codecov.io/bash)